name: Deploy Spotify Playlist

on:
  push:
    branches:
      - main  # Runs workflow when code is pushed to main branch
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs on a Linux environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Fetches your code

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2  # Installs Terraform
        with:
          terraform_version: 1.7.5  # Change to latest stable version if needed

      - name: Login to Spotify Auth Proxy
        run: |
          docker run -d -p 27228:27228 --env SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }} --env SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }} --name spotify-auth-proxy ghcr.io/conradludgate/spotify-auth-proxy
          sleep 5  # Wait for the container to start

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform Configuration
        run: terraform apply -auto-approve
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          TF_VAR_api_key: ${{ secrets.API_KEY }}

      - name: Verify Deployment
        run: terraform output || echo "Deployment successful!"

      - name: Cleanup
        run: docker stop spotify-auth-proxy && docker rm spotify-auth-proxy



